sudo: required
language:
- c++

services:
  - docker

before_install:
- docker pull macrat/docker-mbed-cli
- cd src
- docker run -v `pwd`:/src/src macrat/docker-mbed-cli config root .
- docker run -v `pwd`:/src/src macrat/docker-mbed-cli deploy
- docker run -v `pwd`:/src/src macrat/docker-mbed-cli compile -m LPC1768

- cd project-name
- ls

script:
- bundle exec rake test
