sudo: required

services:
  - docker

before_install:
- docker pull macrat/docker-mbed-cli
- docker run --rm -v `pwd`:/src macrat/docker-mbed-cli new project-name
- cd project-name
- ls

docker run --rm -v `pwd`:/src macrat/docker-mbed-cli compile -m BOARD_NAME

script:
- bundle exec rake test
