sudo: required

language:
- c++
services:
  - docker

before_install:
- docker pull macrat/docker-mbed-cli
- docker run --rm -v `pwd`:/src macrat/docker-mbed-cli compile -m LPC1768

- cd project-name
- ls

script:
- bundle exec rake test
